// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq-e9KhWDYluJdWvrXxi6htb6uwvlpWRo',
    appId: '1:92033409688:android:59686f9a4d3f2f07c8e6ed',
    messagingSenderId: '92033409688',
    projectId: 'wochat-29ac1',
    storageBucket: 'wochat-29ac1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1u8VOJHrxTBgHUPtKMR8E-a6kNo1jSk4',
    appId: '1:92033409688:ios:f9964ed13dfeec90c8e6ed',
    messagingSenderId: '92033409688',
    projectId: 'wochat-29ac1',
    storageBucket: 'wochat-29ac1.appspot.com',
    androidClientId: '92033409688-e7ahufrje4b035blghec85adlhu0ofmi.apps.googleusercontent.com',
    iosClientId: '92033409688-4hrmis2gpsf7gg4nl4m1nc9mspdg59ap.apps.googleusercontent.com',
    iosBundleId: 'com.example.woChat',
  );
}
